name: movie_database
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  bloc: null
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.2.0
  google_fonts: ^6.1.0
  injectable: ^1.5.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  share_plus: ^4.0.3
  stroke_text: any

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/logp.jpg
    - assets/lo.png
